### ISSUE TITLE
cannot import name_pixel search

### ISSUE THREAD

**Issue by alicemacente** [ElsevierSoftwareX/SOFTX-D-17-00061#10]
Hi Erika,
 I seem to have the same issue posted here about a month ago about pixel search.

C:\Program Files\TomoWarp2>python TomoWarp2.py --desktop
C:\Program Files\TomoWarp2\tools\tifffile.py:156: UserWarning: failed to import the optional _tifffile C extension module.
Loading of some compressed images will be slow.
Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
"failed to import the optional _tifffile C extension module.\n"
Traceback (most recent call last):
File "TomoWarp2.py", line 30, in 
from tomowarp_runfile import tomowarp_runfile
File "C:\Program Files\TomoWarp2\tomowarp_runfile.py", line 39, in 
from DIC_setup import DIC_setup
File "C:\Program Files\TomoWarp2\DIC_setup.py", line 44, in 
from DIC_worker import DIC_worker
File "C:\Program Files\TomoWarp2\DIC_worker.py", line 44, in 
from pixel_search.c_code import pixel_search
File "C:\Program Files\TomoWarp2\pixel_search\c_code\pixel_search.py", line 13, in 
from . import _pixel_search
ImportError: cannot import name _pixel_search

Running it on Windows 10 workstation, 64 bit. 

Thanks for the help!
Alice

**Comment by udaya1senanayake** [comment]
I also had the same problem in Windows 10.
rebuild the python extension with

**python setup.py build_ext --inplace**

**Comment by erikatudisco** [comment]
> I also had the same problem in Windows 10.
> rebuild the python extension with
> 
> **python setup.py build_ext --inplace**

Thank you for commenting!
Did this solve the problem for you?

**Comment by udaya1senanayake** [comment]
Yes. Now Its running on Windows 10.

**Comment by alicemacente** [comment]
ah good to know! I will try that too and see how it goes. Thank you guys!

**Comment by alicemacente** [comment]
Ok, so doing what suggested solved the problem to finally open the guy and run Tomowarp.
However, after 2 days of pointless results on my data, I decided to have a look at the examples. Is it normal that for the 3D data,, running the input files included in the folder, I have cc = 0? and no actual result? I do not think it is normal. In 2D though, it seems to work fine. I did not modify the text files, so I am just running the default parameters on the data provided with the code.

Thank you!
Alice

**Comment by erikatudisco** [comment]
Hej Alice,
No, it is not normal but I had other users reporting this. I don't have an explanation right now as the 3D exemple works on other OS. I will have to dig into it as soon as I have access to a Windows 10 machine

**Comment by alicemacente** [comment]
ah okay, no problem then - it is good to know it is just not me!

**Comment by Ada-W-L** [comment]
Hei Erika,
I seem to have a problem:
index -1 is out of bounds for axis 0 with size 0.
Runs in Windows 10, 32bit.
can you tell me how to set this  parameter.
Thank you!
Jamie

**Comment by erikatudisco** [comment]
In Windows if you don't have Visual Studio and, therefore, have to use MinGW to compile the code you have to add an option to the setup:
`python setup.py build_ext --inplace -cmingw32`

**Comment by erikatudisco** [comment]
Hej Jamie,

Can you please send me the log file?

Best regards,
Erika
