### ISSUE TITLE
Getting Started: "No module named tifffile"

### ISSUE THREAD

**Issue by asantos48** [ElsevierSoftwareX/SOFTX-D-17-00061#13]
I am in the Getting Started portion of the manual. While trying to use the examples provided as practice, I am running into the following error. I am not sure how to fix this. 

C:\TomoWarp2>python TomoWarp2.py $examples\2D\DIC_input_parameters
Traceback (most recent call last):
  File "TomoWarp2.py", line 30, in <module>
    from tomowarp_runfile import tomowarp_runfile
  File "C:\TomoWarp2\tomowarp_runfile.py", line 37, in <module>
    from tools.tifffile import imsave
ImportError: No module named tifffile

**Comment by asantos48** [comment]
I changed line 37 in tomowarp_runfile.py to from scipy.misc import imsave and it seems to have resolved this issue.

**Comment by erikatudisco** [comment]
Hej,
This is a weird error, I am glad you could solve the problem I am wondering though if you will be able ti reed the tiff input images if the tifffile module is not working (you can still used other input modes). Please let me know if you get this error again so I can investigate.

**Comment by asantos48** [comment]
Is there something I could have skipped over copying that would have caused this error? I am also now having issues with the pixel_search.c_code module. 
C:\TomoWarp2>python TomoWarp2.py $examples\2D\DIC_input_parameters
Traceback (most recent call last):
  File "TomoWarp2.py", line 30, in <module>
    from tomowarp_runfile import tomowarp_runfile
  File "C:\TomoWarp2\tomowarp_runfile.py", line 39, in <module>
    from DIC_setup import DIC_setup
  File "C:\TomoWarp2\DIC_setup.py", line 44, in <module>
    from DIC_worker import DIC_worker
  File "C:\TomoWarp2\DIC_worker.py", line 43, in <module>
    from pixel_search.c_code import pixel_search
ImportError: No module named pixel_search.c_code

**Comment by erikatudisco** [comment]
This error means that the installation was not successful.
Can you post the output you get when running the setup?

Also, if you wish to receive (very few) news about TomoWarp2 write me an email so I can add you to the mailing list

**Comment by asantos48** [comment]
Are there specific steps of the set up you would like me to run? Otherwise, I will run all the steps involving the command prompt.

Sure, a good email is santos48@purdue.edu .

**Comment by asantos48** [comment]
Step 5 - 12, command prompt output:

C:\Users\abbym>pip install virtualenv
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: virtualenv in c:\python27\lib\site-packages (20.4.7)
Requirement already satisfied: distlib<1,>=0.3.1 in c:\python27\lib\site-packages (from virtualenv) (0.3.2)
Requirement already satisfied: importlib-resources>=1.0; python_version < "3.7" in c:\python27\lib\site-packages (from virtualenv) (3.3.1)
Requirement already satisfied: importlib-metadata>=0.12; python_version < "3.8" in c:\python27\lib\site-packages (from virtualenv) (2.1.1)
Requirement already satisfied: filelock<4,>=3.0.0 in c:\python27\lib\site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: six<2,>=1.9.0 in c:\python27\lib\site-packages (from virtualenv) (1.16.0)
Requirement already satisfied: appdirs<2,>=1.4.3 in c:\python27\lib\site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: typing; python_version < "3.5" in c:\python27\lib\site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (3.10.0.0)
Requirement already satisfied: singledispatch; python_version < "3.4" in c:\python27\lib\site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (3.6.2)
Requirement already satisfied: contextlib2; python_version < "3" in c:\python27\lib\site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (0.6.0.post1)
Requirement already satisfied: pathlib2; python_version < "3" in c:\python27\lib\site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (2.3.5)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in c:\python27\lib\site-packages (from importlib-resources>=1.0; python_version < "3.7"->virtualenv) (1.2.0)
Requirement already satisfied: configparser>=3.5; python_version < "3" in c:\python27\lib\site-packages (from importlib-metadata>=0.12; python_version < "3.8"->virtualenv) (4.0.2)
Requirement already satisfied: scandir; python_version < "3.5" in c:\python27\lib\site-packages (from pathlib2; python_version < "3"->importlib-resources>=1.0; python_version < "3.7"->virtualenv) (1.10.0)

C:\Users\abbym>virtualenv tw2 -p=c:\python27\python.exe
created virtual environment CPython2.7.16.final.0-64 in 5040ms
  creator CPython2Windows(dest=C:\Users\abbym\tw2, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=C:\Users\abbym\AppData\Local\pypa\virtualenv)
    added seed packages: Pillow==6.2.2, backports.functools_lru_cache==1.6.4, cycler==0.10.0, kiwisolver==1.1.0, matplotlib==2.2.5, numpy==1.16.6, pip==20.3.4, pyparsing==2.4.7, python_dateutil==2.8.1, pytz==2021.1, scipy==1.2.3, setuptools==44.1.1, six==1.16.0, wheel==0.36.2
  activators PythonActivator,FishActivator,BatchActivator,BashActivator,PowerShellActivator

C:\Users\abbym>tw2\Scripts\activate

(tw2) C:\Users\abbym>pip install numpy scipy matplotlib pillow
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Requirement already satisfied: numpy in c:\users\abbym\tw2\lib\site-packages (1.16.6)
Requirement already satisfied: scipy in c:\users\abbym\tw2\lib\site-packages (1.2.3)
Requirement already satisfied: matplotlib in c:\users\abbym\tw2\lib\site-packages (2.2.5)
Requirement already satisfied: pillow in c:\users\abbym\tw2\lib\site-packages (6.2.2)
Requirement already satisfied: six>=1.10 in c:\users\abbym\tw2\lib\site-packages (from matplotlib) (1.16.0)
Requirement already satisfied: pytz in c:\users\abbym\tw2\lib\site-packages (from matplotlib) (2021.1)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\abbym\tw2\lib\site-packages (from matplotlib) (2.8.1)
Requirement already satisfied: backports.functools-lru-cache in c:\users\abbym\tw2\lib\site-packages (from matplotlib) (1.6.4)
Requirement already satisfied: cycler>=0.10 in c:\users\abbym\tw2\lib\site-packages (from matplotlib) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\abbym\tw2\lib\site-packages (from matplotlib) (1.1.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\abbym\tw2\lib\site-packages (from matplotlib) (2.4.7)
Requirement already satisfied: setuptools in c:\users\abbym\tw2\lib\site-packages (from kiwisolver>=1.0.1->matplotlib) (44.1.1)

(tw2) C:\Users\abbym>cd C:\TomoWarp2

(tw2) C:\TomoWarp2>cd pixel_search\c_code

(tw2) C:\TomoWarp2\pixel_search\c_code>python setup.py build_ext --inplace -cmingw32 -D MS_WIN64
running build_ext

(tw2) C:\TomoWarp2\pixel_search\c_code>cd C:\TomoWarp2

(tw2) C:\TomoWarp2>cd tools

(tw2) C:\TomoWarp2\tools>python setup_tifffile_c.py build_ext --inplace -cmingw32 -D MS_WIN64
running build_ext

(tw2) C:\TomoWarp2\tools>

**Comment by asantos48** [comment]
Could it be an issue that my path is not Intel (step 4c in windows installation)? I am attaching a snip.
<img width="260" alt="systemVariables" src="https://user-images.githubusercontent.com/86269625/123701362-bfed6200-d82f-11eb-9eb4-81a1c52de73d.PNG">

**Comment by erikatudisco** [comment]
No, these are just the path already in the environmental variable. 
Havo you added the path to python and swig to that?

**Comment by asantos48** [comment]
Yes. I started to reinstall everything in case I made an error along the way.
I am now on step 10c, and I am getting this error.

(tw2) C:\TomoWarp2\pixel_search\c_code>python setup.py build_ext --inplace -cmingw32 -D MS_WIN64
running build_ext
building '_pixel_search' extension
swigging pixel_search.i to pixel_search_wrap.c
C:\swigwin-4.0.2\swig.exe -python -o pixel_search_wrap.c pixel_search.i
pixel_search.i(1) : Error: Syntax error in input(1).
error: command 'C:\\swigwin-4.0.2\\swig.exe' failed with exit status 1

**Comment by asantos48** [comment]
The last line should read:
error: command 'C:\\swigwin-4.0.2\\swig.exe' failed with exit status 1

**Comment by asantos48** [comment]
The last line should read: 
<img width="400" alt="error" src="https://user-images.githubusercontent.com/86269625/124140522-8c405100-da56-11eb-870c-9bb63789dd55.PNG">
