### ISSUE TITLE
3D example not working

### ISSUE THREAD

**Issue by fabbern** [ElsevierSoftwareX/SOFTX-D-17-00061#5]
Dear developpers,

Your software looks great ! However I run into some frustration : I have installed the code on a Windows system with all required dependencies and the 3D test case does not appear to work even with the provided input files. The computation seems to run smoothly but the output files have no useful information at all :

[DIC_201809121441.txt](https://github.com/ElsevierSoftwareX/SOFTX-D-17-00061/files/2375215/DIC_201809121441.txt)

Playing around with ROIs I can manage to get non zero data :

[DIC.txt](https://github.com/ElsevierSoftwareX/SOFTX-D-17-00061/files/2375222/DIC.txt)

Which makes no sense, I think. Any clue of what is wrong ? The 2D test case works properly !

Thanks for your time !

**Comment by erikatudisco** [comment]
Hej and thank you for your interest in the code!

There seems to be a problem on the memory management when running the code on Windows after new updates (I never encountered this problem before). As a consequence the images and not loaded. In the log file, when everything goes well, you should see a mean value for the two volume. You can try to limit the memory (in the optional parameters tab), this should solve the problem although I understand it is annoying.
I will try to solve this bug as soon as possible.

Cheers,
Erika

P.S. For more help you can drop me an email

**Comment by fabbern** [comment]
Thanks for the super quick support. Actually, the mean value is correct even when the issue happens. 

It seems like a small ROI works quite reliably, but as soon as I include too large "weak correlation" areas (like the cone beam artefact area or void) the computed fields are 0. Does that ring a bell ?

On a related topic, one of the example files has a min gray value threshold set to 70, which eliminates most of the images ;-)

All the best,

Fabien

**Comment by erikatudisco** [comment]
Hej!
I think I need a bit more information and it seems to be a data dependent problem. Can you mail me privately (erika.tudisco@construction.lth.se) and send me a result tsv file?

I'll check the input example file :)

Cheers,
Erika
