### ISSUE TITLE
ImportError: cannot import name pixel_search

### ISSUE THREAD

**Issue by theodoreyang** [ElsevierSoftwareX/SOFTX-D-17-00061#7]
Dear developpers,

An error occurred when I tried to run the software on Linux. The installation is perfect, but it produced an error on the pixel_search module. 

Thanks,

/TomoWarp2/pixel_search/c_code$ python setup.py build_ext --inplace
running build_ext
-------------------------------------------------------------------------------------------------------------------------
/TomoWarp2$ python TomoWarp2.py --desktop
/home/ying/TomoWarp2/tools/tifffile.py:156: UserWarning: failed to import the optional _tifffile C extension module.
Loading of some compressed images will be slow.
Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "failed to import the optional _tifffile C extension module.\n"
Traceback (most recent call last):
  File "TomoWarp2.py", line 30, in <module>
    from tomowarp_runfile import tomowarp_runfile
  File "/home/ying/TomoWarp2/tomowarp_runfile.py", line 39, in <module>
    from DIC_setup import DIC_setup
  File "/home/ying/TomoWarp2/DIC_setup.py", line 44, in <module>
    from DIC_worker import DIC_worker
  File "/home/ying/TomoWarp2/DIC_worker.py", line 44, in <module>
    from pixel_search.c_code import pixel_search
ImportError: cannot import name pixel_search

**Comment by erikatudisco** [comment]
Hej!
The compilation of the c_code was not successful.
Please try compiling again using
python setup.py build_ext
(without the option --inplace)

Cheers,
Erika

**Comment by theodoreyang** [comment]
Thank you so much,
It works!
