### ISSUE TITLE
ImportError: cannot import name _pixel_search_2

### ISSUE THREAD

**Issue by ghost** [ElsevierSoftwareX/SOFTX-D-17-00061#9]
Hello,

The error occured while running the TomoWarp2. I believe the installation was good since I've done it several time.
I am working on Windows 10, and I have installed same version of python(xy),  ming gm, swig with the with the manual.

C:\Program Files\TomoWarp2>python TomoWarp2.py --desktop
C:\Program Files\TomoWarp2\tools\tifffile.py:156: UserWarning: failed to import the optional _tifffile C extension module.
Loading of some compressed images will be slow.
Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
  "failed to import the optional _tifffile C extension module.\n"
Traceback (most recent call last):
  File "TomoWarp2.py", line 30, in <module>
    from tomowarp_runfile import tomowarp_runfile
  File "C:\Program Files\TomoWarp2\tomowarp_runfile.py", line 39, in <module>
    from DIC_setup import DIC_setup
  File "C:\Program Files\TomoWarp2\DIC_setup.py", line 44, in <module>
    from DIC_worker import DIC_worker
  File "C:\Program Files\TomoWarp2\DIC_worker.py", line 44, in <module>
    from pixel_search.c_code import pixel_search
  File "C:\Program Files\TomoWarp2\pixel_search\c_code\pixel_search.py", line 13, in <module>
    from . import _pixel_search
ImportError: cannot import name _pixel_search

Could you help me to solve this?
Best,

**Comment by vivlet** [comment]
@erikatudisco can you help?

**Comment by erikatudisco** [comment]
Hej,

Tack you for your interest in the Software!

Which operating system are you using?

Regards,
Erika


--

Erika Tudisco

Assistant Professor
Division of Geotechnical Engineering, Lund University, Lund, Sweden

Postal Address:
  Geotechnical Engineering
  Dept. of Construction Sciences
  Faculty of Engineering
  Lund University
  P.O. Box 118
  SE-221 00 Lund, Sweden

E-mail: erika.tudisco@construction.lth.se<mailto:erika.tudisco@construction.lth.se>
Web: http://www.geoteknik.lth.se/personal/tudisco-erika/
Tel: +46 46 22 20 356

On Sun, 2020-10-25 at 17:18 -0700, kyubok wrote:

Hello,

I have a problem while running the TomoWarp2. I believe the installation was good, and I did it several time

C:\Program Files\TomoWarp2>python TomoWarp2.py --desktop
C:\Program Files\TomoWarp2\tools\tifffile.py:156: UserWarning: failed to import the optional _tifffile C extension module.
Loading of some compressed images will be slow.
Tifffile.c can be obtained at http://www.lfd.uci.edu/~gohlke/
"failed to import the optional _tifffile C extension module.\n"
Traceback (most recent call last):
File "TomoWarp2.py", line 30, in
from tomowarp_runfile import tomowarp_runfile
File "C:\Program Files\TomoWarp2\tomowarp_runfile.py", line 39, in
from DIC_setup import DIC_setup
File "C:\Program Files\TomoWarp2\DIC_setup.py", line 44, in
from DIC_worker import DIC_worker
File "C:\Program Files\TomoWarp2\DIC_worker.py", line 44, in
from pixel_search.c_code import pixel_search
File "C:\Program Files\TomoWarp2\pixel_search\c_code\pixel_search.py", line 13, in
from . import _pixel_search
ImportError: cannot import name _pixel_search

Could you help me to solve this?
Best,

**Comment by ghost** [comment]
Hello Professor Tudisco,
 
Thank you for your reply!
I am working on WIndos 10. And the output message of installation is shown as:
 
C:\Program Files\TomoWarp2\pixel_search\c_code>python setup.py build_ext
running build_ext
 
I am the same one who mailed you directly. Please ignore one of these mails.
 
Best,
-----Original Message-----
